name: 
on:
  push:
    branches:
      - main
env:
  ghSha: ${{ github.sha }}
  ghToken: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
          fetch-depth: 1
    - name: get tree-sitter cli
      run: | 
          echo '::set-env name=TERM::xterm' 
          make getTreeSitter
    - name: generate and test
      run: |
          bin/tree-sitter generate
          bin/tree-sitter test
          bin/tree-sitter parse examples/*.xq --quiet
    - name: parse examples
      run: bin/tree-sitter parse examples/*.xq
    - name:
      run: bin/tree-sitter query --captures queries/highlights.scm examples/lib.xq
